Refactor Chatbot to use Astrapy instead of JSON API
datastax/astra-db-chatbot-starter pull request #3
Opened 2024-01-23 20:12 UTC by ElenaKusevska

2024-01-31 21:45 UTC, jgillenwater requested changes
I made some suggestions so that we are using consistent env vars across tutorials. I also fixed a couple of minor typos.

2024-01-31 21:45 UTC, jgillenwater commented on .env.example
> +ASTRA_DB_KEYSPACE=
Why did we switch this to KEYSPACE? IIUC, we are using keyspace for CQL/drivers, but namespace for everything else.

2024-01-31 21:45 UTC, jgillenwater commented on README.md
> +- ASTRA_DB_API_ENDPOINT="https://ASTRA_DB_ID-ASTRA_REGIN.apps.astra.datastax.com
```suggestion
- ASTRA_DB_API_ENDPOINT="https://ASTRA_DB_ID-ASTRA_REGION.apps.astra.datastax.com"
```

2024-01-31 21:45 UTC, jgillenwater commented on README.md
> +- SCRAPED_FILE=Scrapped data file location
```suggestion
- SCRAPED_FILE=Scraped data file location
```

2024-01-31 21:45 UTC, jgillenwater commented on api/API_README.md
> +    - SCRAPED_FILE=Scrapped data file location
```suggestion
    - SCRAPED_FILE=Scraped data file location
```

2024-01-31 21:45 UTC, jgillenwater commented on README.md
> +- ASTRA_DB_KEYSPACE=existing Astra Namespace/keyspace in a vector enabled DB
```suggestion
- ASTRA_DB_NAMESPACE=existing Astra DB namespace in vector database
```

2024-01-31 21:45 UTC, jgillenwater commented on api/API_README.md
> +    - ASTRA_DB_KEYSPACE=existing Astra Namespace/keyspace in a vector enabled DB
```suggestion
    - ASTRA_DB_NAMESPACE=existing Astra DB namespace in vector databaseB
```

2024-01-31 21:45 UTC, jgillenwater commented on api/chatbot_utils.py
> +keyspace = os.getenv("ASTRA_DB_KEYSPACE")
```suggestion
keyspace = os.getenv("ASTRA_DB_NAMESPACE")
```

2024-01-31 21:45 UTC, jgillenwater commented on populate_db/create_collection.py
> +keyspace = os.getenv("ASTRA_DB_KEYSPACE")
```suggestion
keyspace = os.getenv("ASTRA_DB_NAMESPACE")
```

2024-01-31 21:45 UTC, jgillenwater commented on populate_db/load_data.py
> +keyspace = os.getenv("ASTRA_DB_KEYSPACE")
```suggestion
keyspace = os.getenv("ASTRA_DB_NAMESPACE")
```

2024-01-31 21:45 UTC, jgillenwater commented on .env.example
> +ASTRA_DB_COLLECTION_NAME=
```suggestion
ASTRA_DB_COLLECTION=
```

2024-01-31 21:45 UTC, jgillenwater commented on README.md
> +- ASTRA_DB_COLLECTION_NAME=Name of collection/table to be created in Astra database
```suggestion
- ASTRA_DB_COLLECTION=Name of collection/table to be created in Astra database
```

2024-01-31 21:45 UTC, jgillenwater commented on api/API_README.md
> +    - ASTRA_DB_COLLECTION_NAME=Name of collection/table to be created in Astra database
```suggestion
    - ASTRA_DB_COLLECTION=Name of collection/table to be created in Astra database
```

2024-01-31 21:45 UTC, jgillenwater commented on api/chatbot_utils.py
> +collection_name = os.getenv("ASTRA_DB_COLLECTION_NAME")
```suggestion
collection_name = os.getenv("ASTRA_DB_COLLECTION")
```

2024-01-31 21:45 UTC, jgillenwater commented on populate_db/create_collection.py
> +collection_name = os.getenv("ASTRA_DB_COLLECTION_NAME")
```suggestion
collection_name = os.getenv("ASTRA_DB_COLLECTION")
```

2024-01-31 21:45 UTC, jgillenwater commented on populate_db/load_data.py
> +collection_name = os.getenv("ASTRA_DB_COLLECTION_NAME")
```suggestion
collection_name = os.getenv("ASTRA_DB_COLLECTION")
```

2024-03-12 17:44 UTC, hc33brackles commented on .env.example
> +ASTRA_DB_KEYSPACE=
@jgillenwater - this did get changed to namespace everywhere else - strongly think we should change it here as well

2024-03-12 17:44 UTC, jgillenwater commented on .env.example
>  ASTRA_DB_KEYSPACE=
```suggestion
ASTRA_DB_NAMESPACE=
```

2024-03-12 17:45 UTC, jgillenwater commented on .env.example
> +ASTRA_DB_KEYSPACE=
Yep. Just submitted the same suggestion.

2024-03-12 20:47 UTC, merged